import {
//   Github,
  Mail,
  Code2,
  Braces,
  Atom,
  Triangle,
  Smartphone,
  Server,
  Layers,
  FileCode,
  GitBranch,
  Database,
  Wind,
  Eye,
  Rocket,
  RefreshCw,
  CreditCard,
  Zap,
  Boxes,
  Link2,
  Globe,
  PenTool,
  ArrowUpRight,
  type LucideIcon,
} from 'lucide-react';

const iconMap: Record<string, LucideIcon> = {
//   github: Github,
  linkedin: Globe,
  mail: Mail,
  code: Code2,
  braces: Braces,
  atom: Atom,
  triangle: Triangle,
  smartphone: Smartphone,
  server: Server,
  layers: Layers,
  'file-code': FileCode,
  'git-branch': GitBranch,
  database: Database,
  wind: Wind,
  eye: Eye,
  rocket: Rocket,
  'refresh-cw': RefreshCw,
  'credit-card': CreditCard,
  zap: Zap,
  boxes: Boxes,
  link: Link2,
  globe: Globe,
  pen: PenTool,
  'arrow-up-right': ArrowUpRight,
};

export function getIcon(name: string): LucideIcon {
  return iconMap[name] ?? Code2;
}
